[workspace]
members = ["akm-core", "apple-kb-monitord", "crates/akmctl", "crates/akm-helper"]
resolver = "2"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }

[workspace.package]
version = "3.3.0"
edition = "2021"
rust-version = "1.91"
license = "GPL-2.0-or-later"

[profile.release]
strip = true
lto = true
opt-level = "s"
