# Maintainer: Han <han@agenceapi.com>
pkgname=apple-kb-monitor
pkgver=3.1.0
pkgrel=5
pkgdesc="Telemetry and key mapping for Apple Bluetooth keyboards (BCM2042/BCM20733): battery, voltage, RSSI, BlueZ battery provider, KDE integration"
arch=('x86_64')
url="https://gitea.pika.agenceapi.fr/adminapi/apple-kb-monitor"
license=('GPL-2.0-or-later')
# apihub-app (eframe/winit) loads wayland/xkbcommon/EGL/GL/X11 with dlopen, so
# ldd does not show them: declared by hand (#156). libcap = setcap in the .install.
depends=('python' 'python-dbus-fast' 'bluez' 'keyd' 'polkit' 'dbus' 'systemd' 'libcap'
         'wayland' 'libxkbcommon' 'libxkbcommon-x11' 'libglvnd'
         'libx11' 'libxcursor' 'libxi' 'libxrandr')
makedepends=('rust' 'gcc')
optdepends=(
    'bluez-utils: bluetoothctl CLI for BT management'
    'libnotify: desktop notifications on low battery'
)
options=('!lto')   # C-LTO objects from ring break the Rust link (rust-lld)
backup=('etc/keyd/apple-keyboard.conf' 'etc/modprobe.d/hid_apple.conf')
install=apple-kb-monitor.install
# makepkg only resolves local sources by basename in $startdir, so files in
# subdirectories (systemd/, udev/, ...) are installed directly from $startdir.
source=(
    'apple-kb-monitor'
    'com.agenceapi.AppleKbMonitor.desktop'
)
sha256sums=('SKIP' 'SKIP')

build() {
    # apihub-app (Rust GUI)
    cd "$startdir/apihub-app"
    cargo build --release --workspace --target-dir target

    # rssi-helper (C): the only binary carrying cap_net_admin (file capability
    # applied by apple-kb-monitor.install, see post_install)
    gcc $CFLAGS $LDFLAGS -Wall -Wextra -o "$startdir/rssi-helper" "$startdir/rssi-helper.c"
}

package() {
    # ── Binaries ────────────────────────────────────────────────────────
    install -Dm755 "$srcdir/apple-kb-monitor"                        "$pkgdir/usr/bin/apple-kb-monitor"
    install -Dm755 "$startdir/apihub-app/target/release/apihub-app" "$pkgdir/usr/bin/apihub-app"
    install -Dm755 "$startdir/apihub-app/target/release/apple-kb-monitord" "$pkgdir/usr/bin/apple-kb-monitord"
    install -Dm755 "$startdir/apihub-app/target/release/akmctl"             "$pkgdir/usr/bin/akmctl"
    install -Dm755 "$startdir/apihub-app/target/release/akm-helper"         "$pkgdir/usr/lib/apple-kb-monitor/akm-helper"

    # akmctl: shell completions and man page, generated by the binary itself
    "$pkgdir/usr/bin/akmctl" completions bash | install -Dm644 /dev/stdin "$pkgdir/usr/share/bash-completion/completions/akmctl"
    "$pkgdir/usr/bin/akmctl" completions zsh  | install -Dm644 /dev/stdin "$pkgdir/usr/share/zsh/site-functions/_akmctl"
    "$pkgdir/usr/bin/akmctl" completions fish | install -Dm644 /dev/stdin "$pkgdir/usr/share/fish/vendor_completions.d/akmctl.fish"
    "$pkgdir/usr/bin/akmctl" man              | install -Dm644 /dev/stdin "$pkgdir/usr/share/man/man1/akmctl.1"

    # polkit action for the privileged fnmode helper (pkexec akm-helper)
    install -Dm644 "$startdir/polkit/com.agenceapi.AppleKbMonitor.policy" "$pkgdir/usr/share/polkit-1/actions/com.agenceapi.AppleKbMonitor.policy"

    # ── RSSI helper (cap_net_admin set in post_install, not here: setcap is
    #    not possible under fakeroot and xattrs are not reliably kept) ────
    install -Dm755 "$startdir/rssi-helper"                          "$pkgdir/usr/lib/apple-kb-monitor/rssi-helper"

    # ── systemd user services: apple-kb-monitord (single keyboard owner) and
    #    the legacy Python daemon (Conflicts= with each other) ────────────
    install -Dm644 "$startdir/systemd/apple-kb-monitord.service"         "$pkgdir/usr/lib/systemd/user/apple-kb-monitord.service"
    install -Dm644 "$startdir/systemd/apple-kb-monitor.service"          "$pkgdir/usr/lib/systemd/user/apple-kb-monitor.service"
    install -Dm644 "$startdir/dbus/com.agenceapi.AppleKbMonitor1.service" "$pkgdir/usr/share/dbus-1/services/com.agenceapi.AppleKbMonitor1.service"

    # ── udev + keyd + modprobe ──────────────────────────────────────────
    install -Dm644 "$startdir/udev/70-apple-kb-hidraw.rules"          "$pkgdir/usr/lib/udev/rules.d/70-apple-kb-hidraw.rules"
    install -Dm644 "$startdir/udev/README.md"                         "$pkgdir/usr/share/doc/apple-kb-monitor/udev-README.md"
    install -Dm644 "$startdir/keyd/apple-keyboard.conf"               "$pkgdir/etc/keyd/apple-keyboard.conf"
    install -Dm644 "$startdir/modprobe/hid_apple.conf"                    "$pkgdir/etc/modprobe.d/hid_apple.conf"

    # ── Icons ───────────────────────────────────────────────────────────
    install -Dm644 "$startdir/icons/apihub-scarab.svg"                 "$pkgdir/usr/share/icons/hicolor/scalable/apps/apihub-scarab.svg"
    # dynamic tray icons (battery level steps, charging, disconnected, ...)
    for svg in "$startdir"/icons/hicolor/scalable/status/*.svg; do
        install -Dm644 "$svg" "$pkgdir/usr/share/icons/hicolor/scalable/status/$(basename "$svg")"
    done

    # ── Desktop entry ───────────────────────────────────────────────────
    install -Dm644 "$srcdir/com.agenceapi.AppleKbMonitor.desktop"                "$pkgdir/usr/share/applications/com.agenceapi.AppleKbMonitor.desktop"
    install -Dm644 "$startdir/dbus/com.agenceapi.AppleKbMonitor.service" "$pkgdir/usr/share/dbus-1/services/com.agenceapi.AppleKbMonitor.service"

    # ── Plasma widget ───────────────────────────────────────────────────
    local plasma_dir="$pkgdir/usr/share/plasma/plasmoids/com.agenceapi.devicehub"
    install -dm755 "$plasma_dir/contents/ui"
    install -Dm644 "$startdir/plasma/com.agenceapi.devicehub/metadata.json" "$plasma_dir/metadata.json"
    for qml in "$startdir/plasma/com.agenceapi.devicehub/contents/ui/"*.qml; do
        install -Dm644 "$qml" "$plasma_dir/contents/ui/$(basename "$qml")"
    done
}
