# Maintainer: Han <han@agenceapi.com>
pkgname=apple-kb-monitor
pkgver=3.1.0
pkgrel=21
pkgdesc="Telemetry and key mapping for Apple Bluetooth keyboards (BCM2042/BCM20733): battery, voltage, RSSI, BlueZ battery provider, KDE integration"
arch=('x86_64')
url="https://gitea.pika.agenceapi.fr/adminapi/apple-kb-monitor"
license=('GPL-2.0-or-later')
# apihub-app (eframe/winit) loads wayland/xkbcommon/EGL/GL/X11 with dlopen, so
# ldd does not show them: declared by hand (#156). libcap = setcap in the .install.
depends=('bluez' 'polkit' 'dbus' 'systemd' 'libcap'
         'wayland' 'libxkbcommon' 'libxkbcommon-x11' 'libglvnd'
         'libx11' 'libxcursor' 'libxi' 'libxrandr'
         # System Settings module "Clavier Apple" (kcm/, #250): Plasma 6 only
         # loads a KCM from a plugin, linked to these (QML pages inside)
         'qt6-base' 'qt6-declarative' 'kcmutils' 'ki18n' 'kcoreaddons' 'kirigami')
makedepends=('rust' 'gcc' 'gettext' 'cmake' 'extra-cmake-modules')
optdepends=(
    'bluez-utils: bluetoothctl CLI for BT management'
    'libnotify: desktop notifications on low battery'
    'keyd: optional F3-F6 macros (example config in /usr/share/doc/apple-kb-monitor/examples/keyd)'
)
options=('!lto')   # C-LTO objects from ring break the Rust link (rust-lld)
backup=('etc/modprobe.d/hid_apple.conf' 'etc/apple-kb-monitor/hid-suspend.conf')
install=apple-kb-monitor.install
# makepkg only resolves local sources by basename in $startdir, so files in
# subdirectories (systemd/, udev/, ...) are installed directly from $startdir.
#
# Sources and integrity (#14). This PKGBUILD lives INSIDE the source tree and
# builds that tree: there is no published source archive (the Gitea forge is
# internal, 403 from the Internet, and no release tarball or signed tag is
# served), so there is nothing to download and nothing to checksum but the one
# local file below, whose real sha256 is given (never SKIP; refresh with
# `updpkgsums`, checked by tests/check-pkgbuild.sh). What a published source
# repository would allow, and what cannot be done without one:
#   - source=("git+$url.git#tag=v$pkgver") with its b2sum, or a release tarball;
#   - building in "$srcdir" only, hence in a clean chroot (extra-x86_64-build):
#     today build() and package() read "$startdir", which a chroot build
#     does not have;
#   - a pkgver() checked against the tag.
# What is done meanwhile: the Rust dependencies are the ones of Cargo.lock and
# no others (`cargo fetch --locked` in prepare(), `cargo build --locked` in
# build(): a Cargo.lock that does not match Cargo.toml fails the build instead
# of being silently rewritten), each crate being verified by cargo against the
# checksum recorded in Cargo.lock.
source=(
    'com.agenceapi.AppleKbMonitor.desktop'
)
sha256sums=('d3d4b33665fc9871a873e62d9f55f9f3a55434801d457bd589f10597aee494d6')

prepare() {
    cd "$startdir/apihub-app"
    cargo fetch --locked --target "$(rustc --print host-tuple)"
}

build() {
    # apihub-app (Rust GUI)
    cd "$startdir/apihub-app"
    cargo build --locked --release --workspace --target-dir target

    # rssi-helper (C): the only binary carrying cap_net_admin (file capability
    # applied by apple-kb-monitor.install, see post_install)
    gcc $CFLAGS $LDFLAGS -Wall -Wextra -o "$startdir/rssi-helper" "$startdir/rssi-helper.c"

    # System Settings module (#250): minimal C++ plugin + QML pages + .mo
    cmake -S "$startdir/kcm" -B "$srcdir/kcm-build" -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=None -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DBUILD_TESTING=OFF
    cmake --build "$srcdir/kcm-build"
}

package() {
    # ── Binaries ────────────────────────────────────────────────────────
    install -Dm755 "$startdir/apihub-app/target/release/apihub-app" "$pkgdir/usr/bin/apihub-app"
    install -Dm755 "$startdir/apihub-app/target/release/apple-kb-monitord" "$pkgdir/usr/bin/apple-kb-monitord"
    install -Dm755 "$startdir/apihub-app/target/release/akmctl"             "$pkgdir/usr/bin/akmctl"
    install -Dm755 "$startdir/apihub-app/target/release/akm-helper"         "$pkgdir/usr/lib/apple-kb-monitor/akm-helper"
    install -Dm755 "$startdir/apihub-app/target/release/akm-keymap-helper"  "$pkgdir/usr/lib/apple-kb-monitor/akm-keymap-helper"
    install -Dm755 "$startdir/apihub-app/target/release/akm-hid-control"    "$pkgdir/usr/lib/apple-kb-monitor/akm-hid-control"
    # Read-only inspection of the control channel (MTU): its own executable,
    # so its polkit action (no password) is bound to its path alone.
    install -Dm755 "$startdir/apihub-app/target/release/akm-hid-inspect"    "$pkgdir/usr/lib/apple-kb-monitor/akm-hid-inspect"

    # akmctl: shell completions and man page, generated by the binary itself
    "$pkgdir/usr/bin/akmctl" completions bash | install -Dm644 /dev/stdin "$pkgdir/usr/share/bash-completion/completions/akmctl"
    "$pkgdir/usr/bin/akmctl" completions zsh  | install -Dm644 /dev/stdin "$pkgdir/usr/share/zsh/site-functions/_akmctl"
    "$pkgdir/usr/bin/akmctl" completions fish | install -Dm644 /dev/stdin "$pkgdir/usr/share/fish/vendor_completions.d/akmctl.fish"
    "$pkgdir/usr/bin/akmctl" man              | install -Dm644 /dev/stdin "$pkgdir/usr/share/man/man1/akmctl.1"

    # polkit actions: set-fnmode (pkexec akm-helper: hid_apple parameters) and
    # install-keymap (pkexec akm-keymap-helper: udev hwdb of akmctl keymap, #247)
    install -Dm644 "$startdir/polkit/com.agenceapi.AppleKbMonitor.policy" "$pkgdir/usr/share/polkit-1/actions/com.agenceapi.AppleKbMonitor.policy"

    # ── RSSI helper (cap_net_admin, root:akm 0750 and setcap are applied in
    #    post_install, not here: setcap is not possible under fakeroot, xattrs
    #    are not reliably kept and the group does not exist at build time) ──
    install -Dm755 "$startdir/rssi-helper"                          "$pkgdir/usr/lib/apple-kb-monitor/rssi-helper"
    # group "akm" (#209): only its members may run the capability-carrying helper
    install -Dm644 "$startdir/sysusers/apple-kb-monitor.conf"       "$pkgdir/usr/lib/sysusers.d/apple-kb-monitor.conf"

    # ── systemd user service: apple-kb-monitord (single keyboard owner) ──
    install -Dm644 "$startdir/systemd/apple-kb-monitord.service"         "$pkgdir/usr/lib/systemd/user/apple-kb-monitord.service"
    # Enabled for every user by the package's own .wants link (#260: never by
    # `systemctl --global enable` in the scriptlet, whose /etc links outlived
    # the package); opt out: systemctl --user mask apple-kb-monitord.service
    install -dm755 "$pkgdir/usr/lib/systemd/user/default.target.wants"
    ln -s ../apple-kb-monitord.service "$pkgdir/usr/lib/systemd/user/default.target.wants/apple-kb-monitord.service"
    install -Dm644 "$startdir/dbus/com.agenceapi.AppleKbMonitor1.service" "$pkgdir/usr/share/dbus-1/services/com.agenceapi.AppleKbMonitor1.service"
    # ── WillShutdown at shutdown (what macOS sends, #191): the unit stays active
    #    and its ExecStop= asks the daemon; [apple] will_shutdown = false in
    #    config.toml sends nothing; opt out of the unit too:
    #    systemctl --user mask apple-kb-monitor-shutdown.service ──
    install -Dm644 "$startdir/systemd/apple-kb-monitor-shutdown.service" "$pkgdir/usr/lib/systemd/user/apple-kb-monitor-shutdown.service"
    ln -s ../apple-kb-monitor-shutdown.service "$pkgdir/usr/lib/systemd/user/default.target.wants/apple-kb-monitor-shutdown.service"
    # ── HID_CONTROL SUSPEND (0x13) before sleep / EXIT_SUSPEND (0x14) at wake,
    #    as macOS bluetoothd (#244, docs/VEILLE-HID.md): SYSTEM units (root,
    #    pidfd_getfd on bluetoothd). OFF by default since 2026-10-02 (SUSPEND
    #    measured harmful: the keyboard stays mute), in the packaged file AND in
    #    the code (file or key absent = disabled); opt in:
    #    enabled = true in /etc/apple-kb-monitor/hid-suspend.conf ──
    install -Dm644 "$startdir/systemd/apple-kb-monitor-suspend.service" "$pkgdir/usr/lib/systemd/system/apple-kb-monitor-suspend.service"
    install -Dm644 "$startdir/systemd/apple-kb-monitor-resume.service"  "$pkgdir/usr/lib/systemd/system/apple-kb-monitor-resume.service"
    install -Dm644 "$startdir/systemd/hid-suspend.conf"                 "$pkgdir/etc/apple-kb-monitor/hid-suspend.conf"
    install -dm755 "$pkgdir/usr/lib/systemd/system/sleep.target.wants"
    ln -s ../apple-kb-monitor-suspend.service "$pkgdir/usr/lib/systemd/system/sleep.target.wants/apple-kb-monitor-suspend.service"
    for t in suspend hibernate hybrid-sleep suspend-then-hibernate; do
        install -dm755 "$pkgdir/usr/lib/systemd/system/$t.target.wants"
        ln -s ../apple-kb-monitor-resume.service "$pkgdir/usr/lib/systemd/system/$t.target.wants/apple-kb-monitor-resume.service"
    done
    install -Dm644 "$startdir/docs/VEILLE-HID.md" "$pkgdir/usr/share/doc/apple-kb-monitor/VEILLE-HID.md"
    # ── self-check every 15 min (akmctl selftest), enabled for every user;
    #    opt out: systemctl --user mask apple-kb-monitor-selfcheck.timer ──
    install -Dm644 "$startdir/systemd/apple-kb-monitor-selfcheck.service" "$pkgdir/usr/lib/systemd/user/apple-kb-monitor-selfcheck.service"
    install -Dm644 "$startdir/systemd/apple-kb-monitor-selfcheck.timer"   "$pkgdir/usr/lib/systemd/user/apple-kb-monitor-selfcheck.timer"
    install -dm755 "$pkgdir/usr/lib/systemd/user/timers.target.wants"
    ln -s ../apple-kb-monitor-selfcheck.timer "$pkgdir/usr/lib/systemd/user/timers.target.wants/apple-kb-monitor-selfcheck.timer"
    install -Dm644 "$startdir/docs/QA-AUTOMATIQUE.md" "$pkgdir/usr/share/doc/apple-kb-monitor/QA-AUTOMATIQUE.md"

    # ── udev + modprobe (+ keyd example, never active by default: #246) ──
    install -Dm644 "$startdir/udev/70-apple-kb-hidraw.rules"          "$pkgdir/usr/lib/udev/rules.d/70-apple-kb-hidraw.rules"
    install -Dm644 "$startdir/udev/README.md"                         "$pkgdir/usr/share/doc/apple-kb-monitor/udev-README.md"
    install -Dm644 "$startdir/keyd/apple-keyboard.conf"               "$pkgdir/usr/share/doc/apple-kb-monitor/examples/keyd/apple-keyboard.conf"
    install -Dm644 "$startdir/docs/KEYD.md"                           "$pkgdir/usr/share/doc/apple-kb-monitor/KEYD.md"
    # special keys and manual mapping (#247); the hwdb file itself is written
    # only by `akmctl keymap apply`, never by the package (default = no change)
    install -Dm644 "$startdir/docs/TOUCHES.md"                        "$pkgdir/usr/share/doc/apple-kb-monitor/TOUCHES.md"
    install -Dm644 "$startdir/modprobe/hid_apple.conf"                    "$pkgdir/etc/modprobe.d/hid_apple.conf"

    # ── Icons ───────────────────────────────────────────────────────────
    install -Dm644 "$startdir/icons/apihub-scarab.svg"                 "$pkgdir/usr/share/icons/hicolor/scalable/apps/apihub-scarab.svg"
    # dynamic tray icons (battery level steps, charging, disconnected, ...)
    for svg in "$startdir"/icons/hicolor/scalable/status/*.svg; do
        install -Dm644 "$svg" "$pkgdir/usr/share/icons/hicolor/scalable/status/$(basename "$svg")"
    done

    # ── Desktop entry ───────────────────────────────────────────────────
    install -Dm644 "$srcdir/com.agenceapi.AppleKbMonitor.desktop"                "$pkgdir/usr/share/applications/com.agenceapi.AppleKbMonitor.desktop"
    # KNotification events (docs/NOTIFICATIONS.md, #249): makes the daemon an
    # application of System Settings > Notifications (popup, sound, history, DND).
    install -Dm644 "$startdir/data/apple-kb-monitor.notifyrc"                    "$pkgdir/usr/share/knotifications6/apple-kb-monitor.notifyrc"
    install -Dm644 "$startdir/dbus/com.agenceapi.AppleKbMonitor.service" "$pkgdir/usr/share/dbus-1/services/com.agenceapi.AppleKbMonitor.service"

    # ── System Settings → Input Devices → Keyboard → Apple Keyboard (#250):
    #    lib/qt6/plugins/plasma/kcms/systemsettings/kcm_applekeyboard.so,
    #    share/applications/kcm_applekeyboard.desktop, fr .mo ──
    DESTDIR="$pkgdir" cmake --install "$srcdir/kcm-build"
    install -Dm644 "$startdir/docs/KCM.md" "$pkgdir/usr/share/doc/apple-kb-monitor/KCM.md"

    # ── Plasma widget ───────────────────────────────────────────────────
    local plasma_dir="$pkgdir/usr/share/plasma/plasmoids/com.agenceapi.devicehub"
    install -dm755 "$plasma_dir/contents/ui"
    install -Dm644 "$startdir/plasma/com.agenceapi.devicehub/metadata.json" "$plasma_dir/metadata.json"
    for qml in "$startdir/plasma/com.agenceapi.devicehub/contents/ui/"*.qml "$startdir/plasma/com.agenceapi.devicehub/contents/ui/"*.js; do
        install -Dm644 "$qml" "$plasma_dir/contents/ui/$(basename "$qml")"
    done
    # French translation of the widget (#114): gettext catalogue compiled here,
    # loaded by Plasma's i18n() from the system locale directory.
    msgfmt -o "$srcdir/plasma_applet_com.agenceapi.devicehub.mo" "$startdir/plasma/po/fr.po"
    install -Dm644 "$srcdir/plasma_applet_com.agenceapi.devicehub.mo" \
        "$pkgdir/usr/share/locale/fr/LC_MESSAGES/plasma_applet_com.agenceapi.devicehub.mo"
}
