[ids]
05ac:0256

[main]
# F3-F6 remappés
f3 = macro(M-z)
scale = macro(M-z)
dashboard = macro(M-g)
f5 = macro(M-l)
kbdillumdown = macro(M-l)
numlock = macro(M-d)
f6 = macro(M-d)
kbdillumup = macro(M-d)

# F1/F2: PASSTHROUGH — keyd ne touche pas, passe au système
# (pas de remap = le keycode passe tel quel vers KWin)
