//! Translated `--help`: clap texts go through gettext after the command tree is built.
//!
//! xgettext cannot read doc comments, so `cli_strings.rs` lists every help text as a
//! `tr!` call; the `cli_strings_are_current` test regenerates it when
//! `AKM_REGEN_CLI_STRINGS=1` and fails when it is stale.

use akm_core::i18n::gettext;
use akm_core::tr;
use clap::Command;

/// Built command tree with every help text, heading and template translated.
pub fn localized(mut cmd: Command) -> Command {
    cmd.build();
    walk(cmd)
}

fn walk(mut cmd: Command) -> Command {
    if let Some(s) = cmd.get_about().map(ToString::to_string) {
        cmd = cmd.about(gettext(&s));
    }
    if let Some(s) = cmd.get_long_about().map(ToString::to_string) {
        cmd = cmd.long_about(gettext(&s));
    }
    if let Some(s) = cmd.get_after_help().map(ToString::to_string) {
        cmd = cmd.after_help(gettext(&s));
    }
    if let Some(s) = cmd.get_after_long_help().map(ToString::to_string) {
        cmd = cmd.after_long_help(gettext(&s));
    }
    let options = leak(tr!("Options"));
    let arguments = leak(tr!("Arguments"));
    cmd = cmd.mut_args(|mut a| {
        if let Some(h) = a.get_help().map(ToString::to_string) {
            a = a.help(gettext(&h));
        }
        if let Some(h) = a.get_long_help().map(ToString::to_string) {
            a = a.long_help(gettext(&h));
        }
        let heading = match a.get_help_heading() {
            Some(h) => leak(gettext(h)),
            None if a.is_positional() => arguments,
            None => options,
        };
        a.help_heading(heading)
    });
    let usage = tr!("Usage:");
    cmd = cmd
        .subcommand_help_heading(leak(tr!("Commands")))
        .help_template(format!(
            "{{before-help}}{{about-with-newline}}\n{usage} {{usage}}\n\n{{all-args}}{{after-help}}"
        ));
    cmd.mut_subcommands(walk)
}

/// clap headings want `&'static str`; the CLI builds its tree once per run.
fn leak(s: String) -> &'static str {
    Box::leak(s.into_boxed_str())
}

/// Every translatable text of the tree, in walk order, without duplicates.
#[cfg(test)]
pub fn strings(cmd: &Command) -> Vec<String> {
    fn rec(cmd: &Command, out: &mut Vec<String>) {
        let mut push = |s: Option<String>| {
            if let Some(s) = s.filter(|s| !s.trim().is_empty()) {
                if !out.contains(&s) {
                    out.push(s);
                }
            }
        };
        push(cmd.get_about().map(ToString::to_string));
        push(cmd.get_long_about().map(ToString::to_string));
        push(cmd.get_after_help().map(ToString::to_string));
        push(cmd.get_after_long_help().map(ToString::to_string));
        for a in cmd.get_arguments() {
            push(a.get_help().map(ToString::to_string));
            push(a.get_long_help().map(ToString::to_string));
            push(a.get_help_heading().map(ToString::to_string));
        }
        for s in cmd.get_subcommands() {
            rec(s, out);
        }
    }
    let mut out = Vec::new();
    rec(cmd, &mut out);
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::Cli;
    use clap::CommandFactory;
    use std::fmt::Write as _;

    fn generated() -> String {
        let mut cmd = Cli::command();
        cmd.build();
        let mut s = String::from(
            "//! Generated by `AKM_REGEN_CLI_STRINGS=1 cargo test -p akmctl cli_strings_are_current`.\n\
             //! Lists the clap help texts for xgettext; compiled for the freshness test only.\n\n\
             use akm_core::tr;\n\n\
             pub fn msgids() -> Vec<String> {\n    vec![\n",
        );
        for t in strings(&cmd) {
            let _ = writeln!(s, "        tr!({t:?}),");
        }
        s.push_str("    ]\n}\n");
        s
    }

    #[test]
    fn no_possible_value_has_a_help_of_its_own() {
        // walk() and strings() never see possible-value help: it would stay English.
        fn rec(cmd: &Command) {
            for a in cmd.get_arguments() {
                for v in a.get_possible_values() {
                    assert!(v.get_help().is_none(), "{} {}", a.get_id(), v.get_name());
                }
            }
            cmd.get_subcommands().for_each(rec);
        }
        let mut cmd = Cli::command();
        cmd.build();
        rec(&cmd);
    }

    #[test]
    fn cli_strings_are_current() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/src/cli_strings.rs");
        let want = generated();
        if std::env::var_os("AKM_REGEN_CLI_STRINGS").is_some() {
            std::fs::write(path, &want).unwrap();
        }
        let have = std::fs::read_to_string(path).unwrap_or_default();
        let mut cmd = Cli::command();
        cmd.build();
        assert_eq!(crate::cli_strings::msgids().len(), strings(&cmd).len());
        assert!(
            have == want,
            "src/cli_strings.rs is stale: run AKM_REGEN_CLI_STRINGS=1 cargo test -p akmctl cli_strings_are_current, then scripts/update-po.sh"
        );
    }

    #[test]
    fn localized_help_keeps_the_english_text_without_catalog() {
        let mut cmd = localized(Cli::command());
        let help = cmd.render_help().to_string();
        assert!(help.contains("Usage: akmctl"), "{help}");
        assert!(help.contains("Commands:"), "{help}");
        assert!(help.contains("Options:"), "{help}");
        assert!(
            help.contains("Control and query the Apple keyboard monitor"),
            "{help}"
        );
    }
}
